### ISSUE TITLE
Organize test fakes, data and mocks

### ISSUE THREAD

**Issue by mosdevly** [Tech-Student-Labs/swapi-client-ts#19]
https://github.com/Tech-Student-Labs/swapi-client-ts/blob/a4e04b262f415e4d3f2047c32c105b1605101366/src/app/Character.json#L1

These kinds of files don't belong in app root. If these files are used for testing, they should live in the appropriate test folder in a `data/` folder. 

```
app/
    components/
        tests/
            data/
```

**Comment by mosdevly** [comment]
For clarification: the above is merely an example. **These files should live in the appropriate test folder** and when there are too many of them, you want to organize them into a special folder, such as `data/`

**Comment by 100xlongx** [comment]
https://github.com/Tech-Student-Labs/swapi-client-ts/pull/31
