### ISSUE TITLE
Planets, Characters, and Species services: export common interface

### ISSUE THREAD

**Issue by mosdevly** [Tech-Student-Labs/swapi-client-ts#24]
https://github.com/Tech-Student-Labs/swapi-client-ts/blob/a4e04b262f415e4d3f2047c32c105b1605101366/src/app/services/planet.service.ts#L6

and here:

https://github.com/Tech-Student-Labs/swapi-client-ts/blob/a4e04b262f415e4d3f2047c32c105b1605101366/src/app/services/species.service.ts#L6

and here:

https://github.com/Tech-Student-Labs/swapi-client-ts/blob/a4e04b262f415e4d3f2047c32c105b1605101366/src/app/services/character.service.ts#L9
If this interface is common to all resources on the SWAPI, then why not make it available to all teams?

Lets move this to `app/shared/` and export it so that everyone can use the interface.

**Comment by 100xlongx** [comment]
https://github.com/Tech-Student-Labs/swapi-client-ts/pull/30
