### ISSUE TITLE
Planet service has duplicate interface

### ISSUE THREAD

**Issue by mosdevly** [Tech-Student-Labs/swapi-client-ts#26]
https://github.com/Tech-Student-Labs/swapi-client-ts/blob/a4e04b262f415e4d3f2047c32c105b1605101366/src/app/services/planet.service.spec.ts#L18

Can remove and use any of the other available `APIResponse` interfaces (see #24 )

**Comment by 100xlongx** [comment]
https://github.com/Tech-Student-Labs/swapi-client-ts/pull/30
